name: Unity Development CD

on:
  push:
    branches:
      - develop
  workflow_dispatch: {}

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
#          path: build
          name: ${{ github.repository }}-${{ github.ref_slug }}
      - run: |
          ls -lah .

