name: Unity Development (Test)

on:
  push:
    branches:
      - develop
  workflow_dispatch: {}

jobs:
  configuration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: |
          MATRIX=$(echo $(cat engines/unity/.github/config/matrix.json) | sed 's/ //g' )
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      artifact_name: ${{ github.event.repository.name }}-${{ github.ref_name }}

  build:
    runs-on: ubuntu-latest
    needs:
      - configuration
    strategy:
      matrix:
        config: ${{ fromJson(needs.configuration.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: engines/unity/Library
          key: engine-unity-development-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            engine-unity-development-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: engines/unity
          targetPlatform: WebGL
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ needs.configuration.outputs.artifact_name }}
          path: build
