name: Itch.io Test

on:
  push:
    branches:
      - develop
  workflow_dispatch: {}

jobs:
  configuration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: |
          MATRIX=$(echo $(cat .github/environments/itch/matrix.json) | sed 's/ //g' )
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  build:
    runs-on: ubuntu-latest
    needs:
      - configuration
    strategy:
      matrix:
        config: ${{ fromJson(needs.configuration.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/upload-artifact@v3
        with:
          path: ./github/environments/itch/index.html
          name: ${{ github.event.repository.name }}-${{ matrix.config.channel }}

#  deployment:
#    runs-on: ubuntu-latest
#    needs:
#      - configuration
#      - build
#    strategy:
#      matrix:
#        config: ${{ fromJson(needs.matrix.outputs.matrix) }}
#    environment:
#      name: itch
#      url: https://jervnorsk.itch.io/stellar-rebirth
#    steps:
#      - uses: actions/download-artifact@v2.0.8
#        with:
#          path: build/${{ matrix.channel }}
#          name: ${{ matrix.config.artifactName }}-${{ matrix.config.channel }}
#      - run: |
#          ls -lah .
##      - uses: KikimoraGames/itch-publish@v0.0.3
##        with:
##          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
##          gameData: .github/environments/itch/index.html
##          itchUsername: ${{env.ITCH_USERNAME}}
##          itchGameId: ${{ env.ITCH_GAME_ID }}
##          buildChannel: ${{ matrix.channel }}
##          buildNumber: ${{ needs.version.outputs.version_hash }}
