name: Unity Development (Test)

on:
  push:
    branches:
      - develop
  workflow_dispatch: {}

jobs:
  configuration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: |
          MATRIX=$(echo $(cat engines/unity/.github/configs/matrix.json) | sed 's/ //g' )
          echo "config=$MATRIX" >> $GITHUB_OUTPUT
          MATRIX=$(echo $(cat .github/environments/matrix.json) | sed 's/ //g' )
          echo "environment=$MATRIX" >> $GITHUB_OUTPUT
    outputs:
      config: ${{ steps.set-matrix.outputs.config }}
      environment: ${{ steps.set-matrix.outputs.environment }}
      artifact_name: ${{ github.event.repository.name }}-${{ github.ref_name }}

#  build:
#    runs-on: ubuntu-latest
#    needs:
#      - configuration
#    strategy:
#      matrix:
#        config: ${{ fromJson(needs.configuration.outputs.config) }}
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/cache@v3
#        with:
#          path: engines/unity/Library
#          key: engine-unity-development-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
#          restore-keys: |
#            engine-unity-development-
#      - uses: game-ci/unity-builder@v2
#        env:
#          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
#          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
#          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
#        with:
#          projectPath: engines/unity
#          targetPlatform: WebGL
#      - uses: actions/upload-artifact@v3
#        with:
#          name: ${{ needs.configuration.outputs.artifact_name }}
#          path: build

  development:
    runs-on: ubuntu-latest
    needs:
      - configuration
#      - build
#    strategy:
#      matrix:
#        config: ${{ fromJson(needs.configuration.outputs.config) }}
#        environment: ${{ fromJson(needs.configuration.outputs.environment) }}
#    environment:
#      name: ${{ matrix.environment.name }}
#      url: ${{ matrix.environment.url }}
    steps:
      - run: |
          echo ${{ needs.configuration.outputs.config }}
          echo ${{ needs.configuration.outputs.environment }}
#      - uses: actions/download-artifact@v2.0.8
#        with:
#          name: ${{ needs.configuration.outputs.artifact_name }}
#      - if: ${{ matrix.environment.name == 'itch' }}
#        uses: KikimoraGames/itch-publish@v0.0.3
#        with:
#          butlerApiKey: ${{ secrets.BUTLER_API_KEY }}
#          itchUsername: ${{ vars.ITCH_USERNAME }}
#          itchGameId: ${{ vars.ITCH_GAME_ID }}
#          buildChannel: ${{ matrix.config.channel }}
#          gameData: ./
