name: Continuous Deployment on GitHub Pages

on:
  push:
    branches:
      - develop
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          ls -lah .
      - uses: actions/checkout@v3
#        with:
#          lfs: true
      - run: |
          ls -lah .
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      - run: |
          ls -lah .
#      - uses: game-ci/unity-builder@v2
#        env:
#          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
#          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
#          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
#        with:
#          projectPath: engines/unity
#          targetPlatform: WebGL
#      - uses: actions/upload-artifact@v3
#        with:
#          path: build
#          name: ${{ github.repository }}-${{ github.ref_slug }}

  deployment:
    runs-on: ubuntu-latest
    steps:
      - run: |
          ls -lah .
      - uses: actions/checkout@v3
      - run: |
          ls -lah .
#      - uses: actions/download-artifact@v2
#        with:
#          path: build
#          name: ${{ github.repository }}-${{ github.ref_slug }}

