name: Itch.io Test

on:
  push:
    branches:
      - develop
  workflow_dispatch: {}

jobs:
  configuration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: |
          MATRIX=$(echo $(cat .github/environments/itch/matrix.json) | sed 's/ //g' )
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      artifact_name: ${{ github.event.repository.name }}

  build:
    runs-on: ubuntu-latest
    needs:
      - configuration
    strategy:
      matrix:
        config: ${{ fromJson(needs.configuration.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ needs.configuration.outputs.artifact_name }}-${{ matrix.config.channel }}
          path: .github/environments/itch/index.html

  deployment:
    runs-on: ubuntu-latest
    needs:
      - configuration
      - build
    strategy:
      matrix:
        config: ${{ fromJson(needs.configuration.outputs.matrix) }}
    environment:
      name: itch
      url: https://jervnorsk.itch.io/stellar-rebirth
    steps:
      - uses: actions/download-artifact@v2.0.8
        with:
          name: ${{ needs.configuration.outputs.artifact_name }}-${{ matrix.config.channel }}
      - run: |
          ls -lah .
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{ secrets.BUTLER_API_KEY }}
          itchUsername: ${{ vars.ITCH_USERNAME }}
          itchGameId: ${{ vars.ITCH_GAME_ID }}
          buildChannel: ${{ matrix.config.channel }}
          gameData: ./
